enqueue:
    transport:
        default: 'sqs'
        sqs:
            key: "%env(SQS_KEY)%"
            secret: "%env(SQS_SECRET)%"
            token: null
            region: 'ap-southeast-1'
            version: '2012-11-05'
    client:
        app_name: null
        prefix: null
        router_queue: accounting_staging_invoice
        default_processor_queue: accounting_staging_invoice

