<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.BW31L9o' shared service.

return $this->privates['.service_locator.BW31L9o'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('invoiceTransformer' => function (): \App\Transformer\InvoiceTransformer {
    return ($this->privates['App\Transformer\InvoiceTransformer'] ?? $this->load('getInvoiceTransformerService.php'));
}));
