<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'accounting.service.invoice' shared autowired service.

include_once $this->targetDirs[3].'/src/AccountingPlatform/Invoice/AdapterInterface.php';
include_once $this->targetDirs[3].'/src/AccountingPlatform/Invoice/OdooAdapter.php';
include_once $this->targetDirs[3].'/src/AccountingPlatform/InvoiceService.php';

return $this->services['accounting.service.invoice'] = new \App\AccountingPlatform\InvoiceService(new \App\AccountingPlatform\Invoice\OdooAdapter(($this->privates['service.library.odoo_client'] ?? $this->load('getService_Library_OdooClientService.php'))));
