<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'accounting.service.creditmemo' shared autowired service.

include_once $this->targetDirs[3].'/src/AccountingPlatform/CreditMemo/AdapterInterface.php';
include_once $this->targetDirs[3].'/src/AccountingPlatform/CreditMemo/OdooAdapter.php';
include_once $this->targetDirs[3].'/src/AccountingPlatform/CreditMemoService.php';

return $this->services['accounting.service.creditmemo'] = new \App\AccountingPlatform\CreditMemoService(new \App\AccountingPlatform\CreditMemo\OdooAdapter(($this->privates['service.library.odoo_client'] ?? $this->load('getService_Library_OdooClientService.php'))));
