<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Enqueue\Symfony\Consumption\ContainerAwareConsumeMessagesCommand' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/symfony/dependency-injection/ContainerAwareInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/dependency-injection/ContainerAwareTrait.php';
include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Symfony/Consumption/LimitsExtensionsCommandTrait.php';
include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Symfony/Consumption/QueueConsumerOptionsCommandTrait.php';
include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Symfony/Consumption/ContainerAwareConsumeMessagesCommand.php';

return $this->services['Enqueue\Symfony\Consumption\ContainerAwareConsumeMessagesCommand'] = new \Enqueue\Symfony\Consumption\ContainerAwareConsumeMessagesCommand(($this->services['Enqueue\Consumption\QueueConsumer'] ?? $this->load('getQueueConsumerService.php')));
