<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Enqueue\Symfony\Client\ConsumeMessagesCommand' shared service.

include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Consumption/QueueConsumer.php';
include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Client/ProcessorRegistryInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/dependency-injection/ContainerAwareInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/dependency-injection/ContainerAwareTrait.php';
include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Symfony/Client/ContainerAwareProcessorRegistry.php';
include_once $this->targetDirs[3].'/vendor/queue-interop/queue-interop/src/PsrProcessor.php';
include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Client/DelegateProcessor.php';
include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Symfony/Consumption/LimitsExtensionsCommandTrait.php';
include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Symfony/Client/SetupBrokerExtensionCommandTrait.php';
include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Symfony/Consumption/QueueConsumerOptionsCommandTrait.php';
include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Symfony/Client/ConsumeMessagesCommand.php';

$a = new \Enqueue\Symfony\Client\ContainerAwareProcessorRegistry(array('Enqueue\\Client\\RouterProcessor' => 'Enqueue\\Client\\RouterProcessor', 'symfony_events' => 'enqueue.events.async_processor'));
$a->setContainer($this);

return $this->services['Enqueue\Symfony\Client\ConsumeMessagesCommand'] = new \Enqueue\Symfony\Client\ConsumeMessagesCommand(new \Enqueue\Consumption\QueueConsumer(($this->services['enqueue.transport.default_null.context'] ?? $this->load('getEnqueue_Transport_DefaultNull_ContextService.php')), ($this->privates['enqueue.consumption.extensions'] ?? $this->load('getEnqueue_Consumption_ExtensionsService.php')), 0, 100), new \Enqueue\Client\DelegateProcessor($a), ($this->services['Enqueue\Client\Meta\QueueMetaRegistry'] ?? $this->load('getQueueMetaRegistryService.php')), ($this->services['enqueue.client.default_null.driver'] ?? $this->load('getEnqueue_Client_DefaultNull_DriverService.php')));
