<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'enqueue.events.async_listener' shared service.

include_once $this->targetDirs[3].'/vendor/enqueue/async-event-dispatcher/AsyncListener.php';

return $this->services['enqueue.events.async_listener'] = new \Enqueue\AsyncEventDispatcher\AsyncListener(($this->services['enqueue.transport.default_null.context'] ?? $this->load('getEnqueue_Transport_DefaultNull_ContextService.php')), ($this->privates['enqueue.events.registry'] ?? $this->load('getEnqueue_Events_RegistryService.php')), 'symfony_events');
