<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'enqueue.client.default_null.driver' shared service.

include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Client/DriverInterface.php';
include_once $this->targetDirs[3].'/vendor/enqueue/null/Client/NullDriver.php';

return $this->services['enqueue.client.default_null.driver'] = new \Enqueue\Null\Client\NullDriver(($this->services['enqueue.transport.default_null.context'] ?? $this->load('getEnqueue_Transport_DefaultNull_ContextService.php')), ($this->privates['enqueue.client.config'] ?? $this->load('getEnqueue_Client_ConfigService.php')), ($this->services['Enqueue\Client\Meta\QueueMetaRegistry'] ?? $this->load('getQueueMetaRegistryService.php')));
