<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'enqueue.transport.default_null.context' shared service.

include_once $this->targetDirs[3].'/vendor/queue-interop/queue-interop/src/PsrContext.php';
include_once $this->targetDirs[3].'/vendor/enqueue/null/NullContext.php';
include_once $this->targetDirs[3].'/vendor/queue-interop/queue-interop/src/PsrConnectionFactory.php';
include_once $this->targetDirs[3].'/vendor/enqueue/null/NullConnectionFactory.php';

return $this->services['enqueue.transport.default_null.context'] = ($this->services['enqueue.transport.default.connection_factory'] ?? $this->services['enqueue.transport.default.connection_factory'] = new \Enqueue\Null\NullConnectionFactory())->createContext();
