<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'enqueue.events.event_dispatcher' shared service.

include_once $this->targetDirs[3].'/vendor/enqueue/async-event-dispatcher/AsyncEventDispatcher.php';

return $this->services['enqueue.events.event_dispatcher'] = new \Enqueue\AsyncEventDispatcher\AsyncEventDispatcher(($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), ($this->services['enqueue.events.async_listener'] ?? $this->load('getEnqueue_Events_AsyncListenerService.php')));
