<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'enqueue.events.php_serializer_event_transofrmer' shared service.

include_once $this->targetDirs[3].'/vendor/enqueue/async-event-dispatcher/EventTransformer.php';
include_once $this->targetDirs[3].'/vendor/enqueue/async-event-dispatcher/PhpSerializerEventTransformer.php';

return $this->services['enqueue.events.php_serializer_event_transofrmer'] = new \Enqueue\AsyncEventDispatcher\PhpSerializerEventTransformer(($this->services['enqueue.transport.default_null.context'] ?? $this->load('getEnqueue_Transport_DefaultNull_ContextService.php')));
