<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'enqueue.consumption.extensions' shared service.

include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Consumption/ExtensionInterface.php';
include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Consumption/EmptyExtensionTrait.php';
include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Client/ConsumptionExtension/SetRouterPropertiesExtension.php';
include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Consumption/Extension/SignalExtension.php';
include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Consumption/Extension/ReplyExtension.php';
include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Client/ConsumptionExtension/FlushSpoolProducerExtension.php';
include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Consumption/ChainExtension.php';
include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Client/ExtensionInterface.php';
include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Client/ConsumptionExtension/ExclusiveCommandExtension.php';

return $this->privates['enqueue.consumption.extensions'] = new \Enqueue\Consumption\ChainExtension(array(0 => new \Enqueue\Client\ConsumptionExtension\SetRouterPropertiesExtension(($this->services['enqueue.client.default_null.driver'] ?? $this->load('getEnqueue_Client_DefaultNull_DriverService.php'))), 1 => ($this->privates['enqueue.client.exclusive_command_extension'] ?? $this->privates['enqueue.client.exclusive_command_extension'] = new \Enqueue\Client\ConsumptionExtension\ExclusiveCommandExtension(array('symfony_events' => 'symfony_events'))), 2 => new \Enqueue\Consumption\Extension\SignalExtension(), 3 => new \Enqueue\Consumption\Extension\ReplyExtension(), 4 => new \Enqueue\Client\ConsumptionExtension\FlushSpoolProducerExtension(($this->services['Enqueue\Client\SpoolProducer'] ?? $this->load('getSpoolProducerService.php')))));
