<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'enqueue.client.exclusive_command_extension' shared service.

include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Consumption/ExtensionInterface.php';
include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Client/ExtensionInterface.php';
include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Consumption/EmptyExtensionTrait.php';
include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Client/ConsumptionExtension/ExclusiveCommandExtension.php';

return $this->privates['enqueue.client.exclusive_command_extension'] = new \Enqueue\Client\ConsumptionExtension\ExclusiveCommandExtension(array('symfony_events' => 'symfony_events'));
