<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'enqueue.events.async_processor' shared service.

include_once $this->targetDirs[3].'/vendor/queue-interop/queue-interop/src/PsrProcessor.php';
include_once $this->targetDirs[3].'/vendor/enqueue/async-event-dispatcher/AsyncProcessor.php';

return $this->services['enqueue.events.async_processor'] = new \Enqueue\AsyncEventDispatcher\AsyncProcessor(($this->privates['enqueue.events.registry'] ?? $this->load('getEnqueue_Events_RegistryService.php')), ($this->services['enqueue.events.event_dispatcher'] ?? $this->load('getEnqueue_Events_EventDispatcherService.php')));
