<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'enqueue.client.config' shared service.

include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Client/Config.php';

return $this->privates['enqueue.client.config'] = new \Enqueue\Client\Config('enqueue', 'app', 'default', 'default', 'default', 'Enqueue\\Client\\RouterProcessor', array());
