<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'enqueue.events.registry' shared service.

include_once $this->targetDirs[3].'/vendor/enqueue/async-event-dispatcher/Registry.php';
include_once $this->targetDirs[3].'/vendor/symfony/dependency-injection/ContainerAwareInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/dependency-injection/ContainerAwareTrait.php';
include_once $this->targetDirs[3].'/vendor/enqueue/async-event-dispatcher/ContainerAwareRegistry.php';

$this->privates['enqueue.events.registry'] = $instance = new \Enqueue\AsyncEventDispatcher\ContainerAwareRegistry(array('/.*/' => 'php_serializer'), array('php_serializer' => 'enqueue.events.php_serializer_event_transofrmer'));

$instance->setContainer($this);

return $instance;
