<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Enqueue\Symfony\Client\FlushSpoolProducerListener' shared service.

include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Symfony/Client/FlushSpoolProducerListener.php';

return $this->services['Enqueue\Symfony\Client\FlushSpoolProducerListener'] = new \Enqueue\Symfony\Client\FlushSpoolProducerListener(($this->services['Enqueue\Client\SpoolProducer'] ?? $this->load('getSpoolProducerService.php')));
