<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Transformer\InvoiceTransformer' shared autowired service.

include_once $this->targetDirs[3].'/src/Transformer/LineItemTransformer.php';
include_once $this->targetDirs[3].'/src/Transformer/InvoiceTransformer.php';

return $this->privates['App\Transformer\InvoiceTransformer'] = new \App\Transformer\InvoiceTransformer(new \App\Transformer\LineItemTransformer());
