<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Enqueue\Symfony\Client\ProduceMessageCommand' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Symfony/Client/ProduceMessageCommand.php';

return $this->services['Enqueue\Symfony\Client\ProduceMessageCommand'] = new \Enqueue\Symfony\Client\ProduceMessageCommand(($this->services['Enqueue\Client\TraceableProducer'] ?? $this->load('getTraceableProducerService.php')));
