<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Enqueue\Consumption\QueueConsumer' shared service.

include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Consumption/QueueConsumer.php';

return $this->services['Enqueue\Consumption\QueueConsumer'] = new \Enqueue\Consumption\QueueConsumer(($this->services['enqueue.transport.default_null.context'] ?? $this->load('getEnqueue_Transport_DefaultNull_ContextService.php')), ($this->privates['enqueue.consumption.extensions'] ?? $this->load('getEnqueue_Consumption_ExtensionsService.php')), 0, 100);
