<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Enqueue\Symfony\Client\Meta\QueuesCommand' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Symfony/Client/Meta/QueuesCommand.php';

return $this->services['Enqueue\Symfony\Client\Meta\QueuesCommand'] = new \Enqueue\Symfony\Client\Meta\QueuesCommand(($this->services['Enqueue\Client\Meta\QueueMetaRegistry'] ?? $this->load('getQueueMetaRegistryService.php')));
