<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Enqueue\Rpc\RpcClient' shared service.

include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Rpc/RpcFactory.php';
include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Rpc/RpcClient.php';

$a = ($this->services['enqueue.transport.default_null.context'] ?? $this->load('getEnqueue_Transport_DefaultNull_ContextService.php'));

return $this->services['Enqueue\Rpc\RpcClient'] = new \Enqueue\Rpc\RpcClient($a, new \Enqueue\Rpc\RpcFactory($a));
