<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service.library.odoo_client' shared autowired service.

include_once $this->targetDirs[3].'/vendor/robroypt/odoo-client/src/Client.php';

return $this->privates['service.library.odoo_client'] = new \OdooClient\Client($this->getEnv('ODOO_HOST'), $this->getEnv('ODOO_DB'), $this->getEnv('ODOO_USER'), $this->getEnv('ODOO_PASS'));
