<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Enqueue\Client\SpoolProducer' shared service.

include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Client/ProducerInterface.php';
include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Client/SpoolProducer.php';

return $this->services['Enqueue\Client\SpoolProducer'] = new \Enqueue\Client\SpoolProducer(($this->services['Enqueue\Client\TraceableProducer'] ?? $this->load('getTraceableProducerService.php')));
