<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Enqueue\Symfony\Client\SetupBrokerCommand' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Symfony/Client/SetupBrokerCommand.php';

return $this->services['Enqueue\Symfony\Client\SetupBrokerCommand'] = new \Enqueue\Symfony\Client\SetupBrokerCommand(($this->services['enqueue.client.default_null.driver'] ?? $this->load('getEnqueue_Client_DefaultNull_DriverService.php')));
