<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Enqueue\Client\TraceableProducer' shared service.

include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Rpc/RpcFactory.php';
include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Client/ExtensionInterface.php';
include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Client/ChainExtension.php';
include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Client/ProducerInterface.php';
include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Client/Producer.php';
include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Client/TraceableProducer.php';
include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Consumption/ExtensionInterface.php';
include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Consumption/EmptyExtensionTrait.php';
include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Client/ConsumptionExtension/ExclusiveCommandExtension.php';

return $this->services['Enqueue\Client\TraceableProducer'] = new \Enqueue\Client\TraceableProducer(new \Enqueue\Client\Producer(($this->services['enqueue.client.default_null.driver'] ?? $this->load('getEnqueue_Client_DefaultNull_DriverService.php')), new \Enqueue\Rpc\RpcFactory(($this->services['enqueue.transport.default_null.context'] ?? $this->load('getEnqueue_Transport_DefaultNull_ContextService.php'))), new \Enqueue\Client\ChainExtension(array(0 => ($this->privates['enqueue.client.exclusive_command_extension'] ?? $this->privates['enqueue.client.exclusive_command_extension'] = new \Enqueue\Client\ConsumptionExtension\ExclusiveCommandExtension(array('symfony_events' => 'symfony_events')))))));
