<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Enqueue\Symfony\Client\Meta\TopicsCommand' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Symfony/Client/Meta/TopicsCommand.php';

return $this->services['Enqueue\Symfony\Client\Meta\TopicsCommand'] = new \Enqueue\Symfony\Client\Meta\TopicsCommand(($this->services['Enqueue\Client\Meta\TopicMetaRegistry'] ?? $this->load('getTopicMetaRegistryService.php')));
