<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Enqueue\Client\Meta\TopicMetaRegistry' shared service.

include_once $this->targetDirs[3].'/vendor/enqueue/enqueue/Client/Meta/TopicMetaRegistry.php';

return $this->services['Enqueue\Client\Meta\TopicMetaRegistry'] = new \Enqueue\Client\Meta\TopicMetaRegistry(array('__router__' => array('processors' => array(0 => 'Enqueue\\Client\\RouterProcessor')), '__command__' => array('processors' => array(0 => 'symfony_events'))));
