#index:
#    path: /
#    controller: App\Controller\DefaultController::index

invoice_create:
    path:     /account/{accountId}/invoice
    controller: App\Controller\InvoiceController::create

invoice_update_date:
    path:     /account/{accountId}/invoice/{invoiceId}/date
    controller: App\Controller\InvoiceController::updateDate

invoice_mark_paid:
    path:     /account/{accountId}/invoice/{invoiceId}/payment-journal/{transactionId}
    controller: App\Controller\InvoiceController::markPaid

cancel_invoice:
    path:     /cancel_invoice/{invoiceId}
    controller: App\Controller\InvoiceController::cancelInvoice

credit_memo_create:
    path:     /credit-memo/{invoiceId}
    controller: App\Controller\CreditMemoController::create

creditmemo_update_date:
    path:     /account/{accountId}/creditmemo/{creditMemoId}/date
    controller: App\Controller\CreditMemoController::updateDate

creditmemo_mark_paid:
    path:     /account/{accountId}/creditmemo/{creditMemoId}/payment-journal/{transactionId}
    controller: App\Controller\CreditMemoController::markPaid

cancel_creditmemo:
    path:     /cancel_creditmemo/{creditMemoId}
    controller: App\Controller\CreditMemoController::cancelCreditMemo

