#index:
#    path: /
#    controller: App\Controller\DefaultController::index

invoice_create:
    path:     /account/{accountId}/invoice
    controller: App\Controller\InvoiceController::create

invoice_update_date:
    path:     /account/{accountId}/invoice/{invoiceId}/date
    controller: App\Controller\InvoiceController::updateDate

invoice_mark_paid:
    path:     /account/{accountId}/invoice/{invoiceId}/{transactionId}
    controller: App\Controller\InvoiceController::markPaid

cancel_invoice:
    path:     /cancel_invoice/{invoiceId}
    controller: App\Controller\InvoiceController::cancelInvoice