<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNHom5vv\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNHom5vv/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerNHom5vv.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerNHom5vv\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerNHom5vv\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'NHom5vv',
    'container.build_id' => '6705ddf9',
    'container.build_time' => 1531708891,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerNHom5vv');
